### ISSUE TITLE
Add planout-golang as a submodule to Facebook github

### ISSUE THREAD

**Issue by eytan** [URXtech/planout-golang#19]
Hi guys,
I was wondering if you would be interested in adding a submodule link to your repository in facebook/planout/alpha/golang?  There are now a number of ports floating around and I am trying to centralize them for people who are new to PlanOut.  FWIW, I have updated the [PlanOut homepage](http://facebook.github.io/planout/) to call out your implementation.

**Comment by GregBowyer** [comment]
Absolutely, is there anything you need us to do to help?

**Comment by eytan** [comment]
I have no idea how to set it up, so if you can make a PR I would accept it
:)

**Comment by tsujeeth** [comment]
Thanks @eytan !

Reference:
https://github.com/facebook/planout/pull/57
