### ISSUE TITLE
namespace didn't remove experiments from segmentAllocations after invoking RemoveExperiment()

### ISSUE THREAD

**Issue by panjf2000** [URXtech/planout-golang#32]
namespace didn't remove experiments from segmentAllocations after invoking RemoveExperiment() and it caused "panic: runtime error: invalid memory address or nil pointer dereference" in
![image](https://user-images.githubusercontent.com/7496278/42861035-df740b6e-8a8b-11e8-9126-b4031ec7aa1d.png)
![image](https://user-images.githubusercontent.com/7496278/42861047-e9ad8f74-8a8b-11e8-8f27-d64a02314a7f.png)

**Comment by andrewlook** [comment]
@panjf2000 thanks for reporting - this repo is actually not maintained any more, mind submitting an issue over here please? https://github.com/biased-unit/planout-golang

**Comment by panjf2000** [comment]
@andrewlook got it, thanks for your reply！
